name: accuknox-install
description: 'Install knoxctl, kubearmor and discovery engine '
inputs: # disabling these inputs for now
  kubearmor-image: 
    description: 'kubearmor image to be installed'
    required: false
    default: ""
  discovery-engine-image: # we can change it to tag since discovery engine does not have a single image
    description: 'discovery engine image to be installed'
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout actions
      uses: actions/checkout@v3

    # Assuming k3s will be installed by user
    - name: Install knoxctl, KubeArmor and Discovery Engine
      run: |
        tag=$(curl -sL https://knoxctl.accuknox.com/version/latest_version.txt | cut -d "v" -f2) && \
        curl -sLO "https://knoxctl.accuknox.com/binaries/accuknoxcli_${tag}_linux_amd64.tar.gz" && \
        tar -xvzf "accuknoxcli_${tag}_linux_amd64.tar.gz" && \
        chmod +x ./knoxctl && \
        sudo mv ./knoxctl /usr/local/bin

        knoxctl --help 
        knoxctl version
        knoxctl install
      shell: bash

