name: accuknox-install
description: 'Install accuknox-cli, kubearmor and discovery engine '
inputs:
  kubearmor-image: 
    description: 'kubearmor image to be installed'
    required: true
    default: ""
  discovery-engine-image:
    description: 'discovery engine image to be installed'
    required: true
    default: ""
  workload-namespace:
    description: 'workload namespaces'
    required: false
    default: ""


runs:
  using: "composite"
  steps:
    - name: Checkout accuknox-cli repo and install kubearmor and discovery engine
      uses: actions/checkout@v3
      with:
        repository: rajaSahil/accuknox-cli
        ref: feat-report
        path: accuknox-cli

    - name: Install accuknox-cli, KubeArmor and Discovery Engine
      run: |
        cd accuknox-cli
        chmod +x accuknox-cli
        sudo mv accuknox-cli /usr/bin/
        accuknox-cli version
#        make install
#        accuknox-cli version
#
#        setupArgs=""
#        if [ "${{ inputs.kubearmor-image }}" != "" ]; then
#          setupArgs+= " -i ${{ inputs.kubearmor-image }}"
#        fi
#        if [ "${{ inputs.discovery-engine-image }}" != "" ];then
#          setupArgs += " -di ${{ inputs.discovery-engine-image }}"
#        fi
#        if [ "${{ inputs.workload-namespace }}" != "" ];then
#          setupArgs += " -n ${{ inputs.workload-namespace }}"
#        fi
#
#        accuknox-cli install $setupArgs
      shell: bash

branding:
  icon: 'shield'
  color: 'blue'